title: "Zihao's Portfolio"
description: "Engineer & Computer Science student. Personal website, CV, and projects."
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"
repository: "ZihaoFU245/ZihaoFU245.github.io"

author:
  name: "Zihao Fu"
  avatar: "/assets/images/profile.jpg"
  bio: "Engineer, Computer Science student at HKUST. Interested in AI, systems, and more."
  location: "Hong Kong"
  email: "zihaofu12@gmail.com"
  github: "ZihaoFU245"
  linkedin: "zihaofu"

# Navigation
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
