title: "Zihao Fu - Engineer & CS Student"
description: "Personal portfolio and resume of Zihao Fu, focusing on ML and systems engineering"
url: "https://zihaofu245.github.io"
baseurl: ""

author:
  name: "Zihao Fu"
  email: "[your-email@domain.com]"

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap  
  - jekyll-seo-tag

exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - assets/css/input.css
  - README.md
  - Gemfile
  - Gemfile.lock

collections:
  projects:
    output: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
