title: "Zihao's Portfolio"
description: "Engineer & Computer Science student. Personal website, CV, and projects."
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

minimal_mistakes_skin: "aqua"
repository: "ZihaoFU245/ZihaoFU245.github.io"

# Site settings
url: "https://zihaof245.github.io"
baseurl: ""
locale: "en-US"
title_separator: "-"
breadcrumbs: true

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

author:
  name: "Zihao Fu"
  avatar: "/assets/images/profile.jpg"
  bio: "Engineer, Computer Science student at HKUST. Interested in AI, systems, and more."
  location: "Hong Kong"
  email: "zihaofu12@gmail.com"
  github: "ZihaoFU245"
  linkedin: "zihao-fu-198b02374"

# Navigation
masthead_title: "Zihao's Portfolio"
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
